# Generated by Django 5.0.1 on 2024-01-04 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_person_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('A', 'Central Agent'), ('B', 'Labour'), ('C', 'Collaborator'), ('D', 'Others')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('F', 'Fixed'), ('C', 'Consumable'), ('R', 'Renewable'), ('N', 'Non-renewable'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo')], max_length=2)),
                ('description', models.TextField()),
                ('acquisition_date', models.DateField()),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.person')),
            ],
        ),
    ]
