# Generated by Django 5.0.1 on 2024-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_person_name_person_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki')], max_length=2),
        ),
    ]
