# Generated by Django 5.0.1 on 2024-01-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_resources_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili'), ('OT', 'Other')], max_length=2),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('IP', 'Input'), ('OP', 'Output'), ('OT', 'Other')], max_length=2)),
                ('account', models.CharField(choices=[('MN', 'Main'), ('OT', 'Other')], max_length=2)),
                ('origin_location', models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili')], max_length=2)),
                ('destination_location', models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili')], max_length=2)),
                ('argument_explaination', models.TextField()),
                ('authorizer_boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_boss', to='management.person')),
                ('authorizer_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_manager', to='management.person')),
                ('authorizer_secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_secretary', to='management.person')),
                ('destination_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_destination_person', to='management.person')),
                ('origin_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_origin_person', to='management.person')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('project_code', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('F', 'Farming'), ('L', 'Leasing'), ('P', 'Production'), ('I', 'Infrastructure'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili')], max_length=2)),
                ('description', models.TextField()),
                ('initiation_date', models.DateField()),
                ('end_date', models.DateField()),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.person')),
            ],
        ),
    ]
