# Generated by Django 5.0.1 on 2024-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_resources_location_finance_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='amount_in_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
