# Generated by Django 5.0.1 on 2024-01-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_finance_amount_in_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='destination_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_destination_project', to='management.projects'),
        ),
        migrations.AddField(
            model_name='finance',
            name='origin_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_origin_project', to='management.projects'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(choices=[('MN', 'Main'), ('OT', 'Other'), ('KS', 'Kavatsi')], max_length=2),
        ),
        migrations.AlterField(
            model_name='finance',
            name='destination_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_destination_person', to='management.person'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='origin_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_origin_person', to='management.person'),
        ),
    ]
