# Generated by Django 5.0.1 on 2024-01-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_finance_destination_project_finance_origin_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('A', 'Central Agent'), ('B', 'Labour'), ('C', 'Collaborator'), ('D', 'Others'), ('E', 'Boss')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_code',
            field=models.CharField(default='P0001', max_length=30),
        ),
        migrations.AlterField(
            model_name='resources',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
