# Generated by Django 5.0.1 on 2024-01-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_person_position_alter_projects_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('E', 'Boss'), ('A', 'Central Agent'), ('B', 'Labour'), ('C', 'Collaborator'), ('D', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='resources',
            name='acquisition_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
