# Generated by Django 5.0.1 on 2024-01-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_finance_created_at_person_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.person'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_personel_names',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_personel_list', to='management.person'),
        ),
    ]
