# Generated by Django 5.0.1 on 2024-01-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_projects_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
