# Generated by Django 5.0.1 on 2024-01-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='authorizer_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_boss', to='management.person'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='authorizer_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_manager', to='management.person'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='authorizer_secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_secretary', to='management.person'),
        ),
    ]
