# Generated by Django 5.0.1 on 2024-01-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_finance_authorizer_boss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='argument_explaination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='destination_location',
            field=models.CharField(blank=True, choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='origin_location',
            field=models.CharField(blank=True, choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KL', 'Kili')], max_length=2, null=True),
        ),
    ]
