# Generated by Django 5.0.1 on 2024-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_finance_argument_explaination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=models.CharField(choices=[('KL', 'Kighali'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KI', 'Kili'), ('OT', 'Other')], max_length=2),
        ),
    ]
