# Generated by Django 5.0.1 on 2024-01-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_resources_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='location',
            field=models.CharField(choices=[('KL', 'Kighali_vitula'), ('KM', 'Kighali_kaghumo'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KI', 'Kili'), ('OT', 'Other')], max_length=2),
        ),
    ]
