# Generated by Django 5.0.1 on 2024-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_resources_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(choices=[('MN', 'Main'), ('KS', 'Kavatsi'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='finance',
            name='destination_location',
            field=models.CharField(blank=True, choices=[('KL', 'Kighali_vitula'), ('KM', 'Kighali_kaghumo'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KI', 'Kili'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='finance',
            name='origin_location',
            field=models.CharField(blank=True, choices=[('KL', 'Kighali_vitula'), ('KM', 'Kighali_kaghumo'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KI', 'Kili'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='location',
            field=models.CharField(choices=[('KL', 'Kighali_vitula'), ('KM', 'Kighali_kaghumo'), ('KW', 'Kisembwe'), ('KS', 'Kipese'), ('BB', 'Butembo'), ('KK', 'Kasiki'), ('KI', 'Kili'), ('OT', 'Other')], max_length=2),
        ),
    ]
