# Generated by Django 5.0.1 on 2024-01-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_finance_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(choices=[('MN', 'Main'), ('KG', 'Katembo_Syalivene'), ('KS', 'Kavatsi'), ('OT', 'Other')], max_length=2),
        ),
    ]
