# Generated by Django 5.0.1 on 2024-01-10 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_finance_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, choices=[('E', 'Boss'), ('A', 'Agent Bureau'), ('B', 'Ouvrier'), ('E', 'Locataire_nziapanda'), ('C', 'Collaborateur'), ('D', 'Autre')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Comptes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(choices=[('IP', 'Input'), ('OP', 'Output'), ('OT', 'Other')], max_length=2)),
                ('justification', models.TextField(blank=True, choices=[('AV', 'Avance sur salaire'), ('AL', 'Loyer')], max_length=2, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('authorizer_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comptes_authorizer_secretary', to='management.person')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.person')),
            ],
        ),
    ]
