# Generated by Django 5.0.1 on 2024-01-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_finance_destination_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(choices=[('MN', 'Main'), ('KG', 'Katembo_Syalivene'), ('KS', 'Kavatsi'), ('LV', 'Louange_Vikoma'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(choices=[('F', 'Fixed'), ('C', 'Consumable'), ('R', 'Renewable'), ('N', 'Non-renewable'), ('O', 'Other')], max_length=1),
        ),
    ]
