# Generated by Django 5.0.1 on 2024-01-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptes',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
