# Generated by Django 5.0.1 on 2024-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_comptes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptes',
            name='contracted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
