# Generated by Django 5.0.1 on 2024-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_comptes_contracted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='code',
            field=models.CharField(blank=True, default='AA11BB', max_length=6),
        ),
    ]
