# Generated by Django 5.0.1 on 2024-01-21 10:03

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_finance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='code',
            field=models.CharField(default=management.models.generate_unique_code, max_length=6, unique=True),
        ),
    ]
