# Generated by Django 5.0.1 on 2024-01-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_finance_registration_date_projects_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptes',
            name='amount_in_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_personel_names',
            field=models.ManyToManyField(blank=True, related_name='project_personel_list', to='management.person'),
        ),
    ]
