# Generated by Django 5.0.1 on 2024-01-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_alter_finance_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(blank=True, choices=[('MN', 'Main'), ('KG', 'Katembo_Syalivene'), ('KS', 'Kasereka_Kavatsi'), ('LV', 'Louange_Vikoma'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit', models.CharField(choices=[('SC', 'Sac'), ('TG', 'Tige'), ('BX', 'Box'), ('OT', 'Autre')], max_length=2)),
                ('total_units', models.FloatField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_product_name', to='management.resources')),
            ],
        ),
    ]
