# Generated by Django 5.0.1 on 2024-01-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_alter_finance_account_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='account',
            field=models.CharField(blank=True, choices=[('MN', 'Main'), ('KG', 'Katembo_Syalivene'), ('KS', 'Kasereka_Kavatsi'), ('LV', 'Louange_Vikoma'), ('OT', 'Other')], max_length=25, null=True),
        ),
    ]
