# Generated by Django 5.0.1 on 2024-01-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_finance_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptes',
            name='justification',
            field=models.TextField(blank=True, choices=[('AV', 'Salaire'), ('AL', 'Loyer')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_units',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
