# Generated by Django 5.0.1 on 2024-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_alter_finance_destination_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_name',
            new_name='nom_produit',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='product_unit',
            new_name='unite_produit',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='total_units',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='prix_unitaire',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='transaction',
            field=models.CharField(blank=True, choices=[('IP', 'Arrivage'), ('OP', 'Vente'), ('OT', 'Achat')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='transaction',
            field=models.CharField(choices=[('IP', 'Arrivage'), ('OP', 'Vente'), ('OT', 'Achat')], max_length=2),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type_transaction',
            field=models.CharField(choices=[('IP', 'Arrivage'), ('OP', 'Vente'), ('OT', 'Achat')], max_length=2),
        ),
    ]
