# Generated by Django 5.0.1 on 2024-01-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_rename_product_name_stock_nom_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comptes',
            name='transaction',
            field=models.CharField(choices=[('IP', 'Input'), ('OP', 'Output')], max_length=2),
        ),
        migrations.AlterField(
            model_name='finance',
            name='type_transaction',
            field=models.CharField(choices=[('IP', 'Input'), ('OP', 'Output')], max_length=2),
        ),
    ]
