# Generated by Django 5.0.1 on 2024-01-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_stock_date_alter_comptes_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='authorizer_boss',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_boss', to='management.person'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='authorizer_manager',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_manager', to='management.person'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='authorizer_secretary',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_authorizer_secretary', to='management.person'),
        ),
    ]
