
ADDRESS = [
    ('Bandundu', 'Kwilu, Democratic Republic of the Congo'),
    ('Basoko', 'Tshopo, Democratic Republic of the Congo'),
    ('Bena Leka', 'Sankuru, Democratic Republic of the Congo'),
    ('Beni', 'North Kivu, Democratic Republic of the Congo'),
    ('Binga', 'Kwilu, Democratic Republic of the Congo'),
    ('Bolobo', 'Mai-Ndombe, Democratic Republic of the Congo'),
    ('Bolongo', 'Kongo Central, Democratic Republic of the Congo'),
    ('Boma', 'Kongo Central, Democratic Republic of the Congo'),
    ('Bukama', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Bukavu', 'South Kivu, Democratic Republic of the Congo'),
    ('Bulungu', 'Kwilu, Democratic Republic of the Congo'),
    ('Bumba', 'Mongala, Democratic Republic of the Congo'),
    ('Bunia', 'Ituri, Democratic Republic of the Congo'),
    ('Businga', 'Mongala, Democratic Republic of the Congo'),
    ('Buta', 'Bas-Uélé, Democratic Republic of the Congo'),
    ('Butembo', 'Nord-Kivu, Democratic Republic of the Congo'),
    ('Dibaya', 'Kasaï, Democratic Republic of the Congo'),
    ('Dilolo', 'Lualaba, Democratic Republic of the Congo'),
    ('Dima', 'Haut-Uélé, Democratic Republic of the Congo'),
    ('Dungu', 'Haut-Uélé, Democratic Republic of the Congo'),
    ('Gbadolite', 'Nord-Ubangi, Democratic Republic of the Congo'),
    ('Gemena', 'Sud-Ubangi, Democratic Republic of the Congo'),
    ('Gemena', 'Sud-Ubangi, Democratic Republic of the Congo'),
    ('Goma', 'Nord-Kivu, Democratic Republic of the Congo'),
    ('Ilebo', 'Kasaï, Democratic Republic of the Congo'),
    ('Inongo', 'Mai-Ndombe, Democratic Republic of the Congo'),
    ('Isiro', 'Haut-Uélé, Democratic Republic of the Congo'),
    ('Kabalo', 'Tanganyika, Democratic Republic of the Congo'),
    ('Kabare', 'South Kivu, Democratic Republic of the Congo'),
    ('Kabinda', 'Lomami, Democratic Republic of the Congo'),
    ('Kahemba', 'Kwilu, Democratic Republic of the Congo'),
    ('Kalemie', 'Tanganyika, Democratic Republic of the Congo'),
    ('Kalima', 'Maniema, Democratic Republic of the Congo'),
    ('Kambove', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Kambove-Musonoi', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Kamina', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Kampemba', 'Kwilu, Democratic Republic of the Congo'),
    ('Kampene HLmi', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Kampene Mma', 'Maniema, Democratic Republic of the Congo'),
    ('Kananga', 'Kasaï-Central, Democratic Republic of the Congo'),
    ('Kaniama', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Kasangulu', 'Kongo Central, Democratic Republic of the Congo'),
    ('Kasongo', 'Maniema, Democratic Republic of the Congo'),
    ('Kasongo-Lunda', 'Kwango, Democratic Republic of the Congo'),
    ('Kasongo-Mpangu', 'Maniema, Democratic Republic of the Congo'),
    ('Katanda', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Kenge', 'Kwango, Democratic Republic of the Congo'),
    ('Kibombo', 'Kwango, Democratic Republic of the Congo'),
    ('Kikondja HL', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Kikondja L', 'Lomami, Democratic Republic of the Congo'),
    ('Kikwit', 'Kwilu, Democratic Republic of the Congo'),
    ('Kimpese', 'Kongo Central, Democratic Republic of the Congo'),
    ('Kindu', 'Maniema, Democratic Republic of the Congo'),
    ('Kingabwa', 'Kinshasa, Democratic Republic of the Congo'),
    ('Kinsenso', 'Kinshasa, Democratic Republic of the Congo'),
    ('Kipushi', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Kisangani', 'Tshopo, Democratic Republic of the Congo'),
    ('Kisantu', 'Kongo Central, Democratic Republic of the Congo'),
    ('Kolwezi', 'Lualaba, Democratic Republic of the Congo'),
    ('Kongolo', 'Tanganyika, Democratic Republic of the Congo'),
    ('Kutu', 'Kwango, Democratic Republic of the Congo'),
    ('Kwilu-Ngongo', 'Kwilu, Democratic Republic of the Congo'),
    ('Likasi', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Lisala', 'Mongala, Democratic Republic of the Congo'),
    ('Lisenge', 'Kongo Central, Democratic Republic of the Congo'),
    ('Lodja', 'Sankuru, Democratic Republic of the Congo'),
    ('Lomela', 'Kasaï, Democratic Republic of the Congo'),
    ('Luanza', 'Kwango, Democratic Republic of the Congo'),
    ('Lubao HL', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Lubao K', 'Kasaï, Democratic Republic of the Congo'),
    ('Lubefu', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Lubumbashi', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Luebo', 'Kasaï, Democratic Republic of the Congo'),
    ('Lukala', 'Kongo Central, Democratic Republic of the Congo'),
    ('Luputa', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Lusambo', 'Sankuru, Democratic Republic of the Congo'),
    ('Makiso', 'Nord-Kivu, Democratic Republic of the Congo'),
    ('Makobola', 'Kwango, Democratic Republic of the Congo'),
    ('Makungu', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Mambasa', 'Ituri, Democratic Republic of the Congo'),
    ('Mangai Kasaï', 'Kasaï, Democratic Republic of the Congo'),
    ('Mangai Kwilu', 'Kwilu, Democratic Republic of the Congo'),
    ('Manono', 'Tanganyika, Democratic Republic of the Congo'),
    ('Masina', 'Kinshasa, Democratic Republic of the Congo'),
    ('Masisi', 'North Kivu, Democratic Republic of the Congo'),
    ('Matadi', 'Kongo Central, Democratic Republic of the Congo'),
    ('Mbandaka', 'Equateur, Democratic Republic of the Congo'),
    ('Mbanza-Ngungu', 'Kongo Central, Democratic Republic of the Congo'),
    ('Mbuji-Mayi', 'Kasaï-Oriental, Democratic Republic of the Congo'),
    ('Mikondo', 'Kinshasa, Democratic Republic of the Congo'),
    ('Mitwaba', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Moba', 'Tanganyika, Democratic Republic of the Congo'),
    ('Moero', 'Tanganyika, Democratic Republic of the Congo'),
    ('Mongbwalu', 'Ituri, Democratic Republic of the Congo'),
    ('Mubumbano', 'Sud-Kivu, Democratic Republic of the Congo'),
    ('Mweka', 'Kasaï, Democratic Republic of the Congo'),
    ('Mwene-Ditu', 'Lomami, Democratic Republic of the Congo'),
    ('Mwenga', 'Sud-Kivu, Democratic Republic of the Congo'),
    ('Nioki', 'Mai-Ndombe, Democratic Republic of the Congo'),
    ('Nkamba', 'Kongo Central, Democratic Republic of the Congo'),
    ('Oicha', 'Nord-Kivu, Democratic Republic of the Congo'),
    ('Pweto', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Sakania HK', 'Haut-Katanga, Democratic Republic of the Congo'),
    ('Sakania HL', 'Haut-Lomami, Democratic Republic of the Congo'),
    ('Sandoa', 'Maniema, Democratic Republic of the Congo'),
    ('Tshela', 'Kongo Central, Democratic Republic of the Congo'),
    ('Tshikapa', 'Kasaï, Democratic Republic of the Congo'),
    ('Uvira', 'South Kivu, Democratic Republic of the Congo'),
    ('Wamba', 'Haut-Uélé, Democratic Republic of the Congo'),
    ('Watsa', 'Haut-Uélé, Democratic Republic of the Congo'),
    ('Yangambi', 'Tshopo, Democratic Republic of the Congo'),
    ('Yumbi', 'Mai-Ndombe, Democratic Republic of the Congo'),
    ('Zongo', 'Sud-Ubangi, Democratic Republic of the Congo'),
]